### ISSUE TITLE
Im using wine on linux, BRMM loads but whenever i press install, the browser wont load

### ISSUE THREAD

**Issue by Supervisor360** [anonymous-editor/BRMM#9]
is it possible to make a port for linux or allow the ability to open linux browsrs?

**Comment by anonymous-editor** [comment]
> is it possible to make a port for linux or allow the ability to open linux browsrs?

Linux has native Python support, so as long you have the right dependencies and the Python package thing, you should be good.

Also, DO NOT use WINE. It is the worst thing known to mankind.

Before I can actually help you though, what Linux distro are you using?
